### ISSUE TITLE
This repository is in violation of Unity Asset Store's terms.

### ISSUE THREAD

**Issue by EnoxSoftware** [n1ckfg/EP_CV_oF#1]
Hi.
I am a developer of "DibFaceLandmarkDetector".
Your public repository contains the files of the paid Unity asset that I am selling in the asset store.
Could you add the "DibFaceLandmarkDetector" folder to the .ignore file or change the attribute of the repository to private?
I hope that you will understand.
Thank you in advance.

Enox Software

**Comment by n1ckfg** [comment]
Thanks for letting me know--I've removed the folder and added it to the ignore file. Also did this for the org fork.

**Comment by EnoxSoftware** [comment]
Thank you for your quick and polite response.

**Comment by EnoxSoftware** [comment]
Hi n1ckfg.

Thank you for your quick response the other day.
I noticed that the asset files remained included in past commits in your repository.
Could you delete the files completely using the "git filter - branch" command, etc?

Thank you in advance.

Enox Software

**Comment by n1ckfg** [comment]
OK, check it for me now--never used that command before. Should be removed from both forks.

**Comment by EnoxSoftware** [comment]
Thank you for your quick response.
It seems that the files is completely deleted as far as I see.

**Comment by n1ckfg** [comment]
Sure, I'm working on my own Unity Asset Store project so I completely understand.
